# Generated by Django 2.2.4 on 2019-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190830_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('german', 'GERMAN'), ('hindi', 'HINDI'), ('french', 'FRENCH')], max_length=2),
        ),
    ]
